#include QMK_KEYBOARD_H
#ifdef STENO_ENABLE
# include "keymap_steno.h"
#endif

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum layers {
  _QWERTY,
  _RAISE,
  _LOWER,
  _ADJUST,
#ifdef STENO_ENABLE
  _PLOVER
#endif
};

enum custom_keycodes {
  KVM_SW = SAFE_RANGE,
};

#define RAISE MO(_RAISE)
#define LOWER MO(_LOWER)
#define ADJUST MO(_ADJUST)

#ifdef STENO_ENABLE
# define PLOVER DF(_PLOVER)
#else
# define PLOVER _______
#endif
#define EXT_PLV DF(_QWERTY)

#define EU_AA RALT(KC_W)
#define EU_AE RALT(KC_A) #define EU_OE RALT(KC_O)
#define SFT_TAB LSFT_T(KC_TAB)

const uint16_t PROGMEM sd_esc[] = { KC_S, KC_D, COMBO_END};
const uint16_t PROGMEM df_tab[] = { KC_D, KC_F, COMBO_END};
const uint16_t PROGMEM kx_tilde[] = { KC_K, KC_X, COMBO_END};
const uint16_t PROGMEM kl_col[] = { KC_K, KC_L, COMBO_END};

combo_t key_combos[COMBO_COUNT] = {
    COMBO(sd_esc, KC_ESC),
    COMBO(df_tab, KC_TAB),
    COMBO(kx_tilde, KC_TILD),
    COMBO(kl_col, KC_COLN),
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [_QWERTY] = LAYOUT_5x6(
     KC_ESC  , KC_1 , KC_2    , KC_3    , KC_4 , KC_5 ,		KC_6 , KC_7 , KC_8    , KC_9   , KC_0    , KC_GRV          ,
     KC_TAB  , KC_Q , KC_W    , KC_E    , KC_R , KC_T ,		KC_Y , KC_U , KC_I    , KC_O   , KC_P    , KC_MINS         ,
     KC_LCTL , KC_A , KC_S    , KC_D    , KC_F , KC_G ,		KC_H , KC_J , KC_K    , KC_L   , KC_SCLN , KC_QUOT         ,
     KC_LSFT , KC_Z , KC_X    , KC_C    , KC_V , KC_B ,		KC_N , KC_M , KC_COMM , KC_DOT , KC_SLSH , KC_RSFT         ,
		      KC_LEFT , KC_RGHT 				    , KC_DOWN , KC_UP  ,
					  KC_BSPC,  KC_TAB, KC_SPC , KC_ENT ,
					  RAISE  , KC_LGUI, KC_DEL , LOWER  ,
					  KC_LCTL, KC_LALT, KVM_SW , KC_RALT
  ), 
  [_LOWER] = LAYOUT_5x6(
       KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,                KC_F7,   KC_F8,   KC_F9,  KC_F10,  KC_F11,  KC_F12,
     _______, _______,    KC_7,    KC_8,    KC_9, _______,		_______,    KC_7,    KC_8,    KC_9, _______, _______,
     KC_CAPS, _______,    KC_4,    KC_5,    KC_6, _______,              _______,    KC_4,    KC_5,    KC_6, _______, _______,
     _______, _______,    KC_1,    KC_2,    KC_3, _______,		_______,    KC_1,    KC_2,    KC_3, _______, _______,
		          KC_0,  KC_DOT                                                 ,    KC_0,  KC_DOT,
					  _______, _______, _______, _______,
					  ADJUST , _______, _______, ADJUST ,
					  _______, _______, _______, _______ 
  ),
  [_RAISE] = LAYOUT_5x6(
       KC_F1,   KC_F2,   KC_F3,   KC_F4,   KC_F5,   KC_F6,                KC_F7,   KC_F8,   KC_F9,  KC_F10,  KC_F11,  KC_F12,
     _______, KC_EXLM,   KC_AT, KC_HASH,  KC_DLR, KC_PERC,              KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_BSPC,
     KC_CAPS, _______, _______, _______, _______, _______,              KC_MINS,  KC_EQL, KC_LCBR, KC_RCBR, KC_PIPE,  KC_GRV,
     _______, _______, _______, _______, _______, _______,              KC_UNDS, KC_PLUS, KC_LBRC, KC_RBRC, KC_BSLS, KC_TILD,
		       KC_HOME,  KC_END                                                 , KC_PGDN, KC_PGUP,
					  _______, _______, _______, _______,
					  ADJUST , _______, _______, ADJUST ,
					  _______, _______, _______, _______ 
  ),
  /*
  [_NUM] = LAYOUT_5x6(
     KC_F11 ,  KC_F1 ,  KC_F2 ,  KC_F3 ,  KC_F4 ,  KC_F5 ,		 KC_F6 ,  KC_F7 ,  KC_F8 ,  KC_F9 , KC_F10 , KC_F11 ,
     KC_GRV ,  KC_1  ,   KC_2 ,  KC_3  ,   KC_4 ,   KC_5 ,		  KC_6 ,   KC_7 ,   KC_8 , KC_9   , KC_0   , _______,
     _______, _______, _______, _______, _______, _______,		KC_LEFT, KC_DOWN,  KC_UP , KC_RGHT, _______, _______,
     _______, _______, _______, _______, _______, _______,		KC_HOME, KC_PGDN, KC_PGUP, KC_END , _______, _______,
		       _______, _______                                                 , _______, _______,
					  _______, _______, _______, _______,
					  ADJUST , _______, _______, _______,
					  KC_RCTL, _______, _______, _______ 
  ),
  [_SYM] = LAYOUT_5x6(
     KC_F11 ,  KC_F1 ,  KC_F2 ,  KC_F3 ,  KC_F4 ,  KC_F5 ,		 KC_F6 ,  KC_F7 ,  KC_F8 ,  KC_F9 , KC_F10 , KC_F11 ,
     KC_TILD, KC_EXLM,  KC_AT , KC_HASH, KC_DLR ,KC_PERC , 		KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_UNDS,
     _______, _______, _______, KC_LPRN, KC_LCBR,KC_LBRC ,		KC_RBRC, KC_RCBR, KC_RPRN, _______, _______, _______,
     _______, _______, _______, _______, _______,_______ ,		_______, _______, _______, _______, _______, _______,
		       KC_LCBR, KC_RCBR                                                 , _______, _______,
					  _______, _______, _______, _______,
					  _______, _______, _______, ADJUST ,
					  _______, _______, _______, _______ 
  ),
  [_RAISE] = LAYOUT_5x6(
     _______, _______, _______, _______, _______, _______,		_______, _______, _______, _______, _______, _______,
     _______, KC_EXLM,  KC_AT ,  KC_UP , KC_LCBR, KC_RCBR,		KC_BSLS,   KC_7 ,   KC_8 ,   KC_9 , KC_ASTR, _______,
     _______, KC_HASH, KC_LEFT, KC_DOWN, KC_RGHT, KC_DLR ,		KC_EQL ,   KC_4 ,   KC_5 ,   KC_6 , KC_MINS, _______,
     _______, KC_LBRC, KC_RBRC, KC_LPRN, KC_RPRN, KC_AMPR,		KC_GRV ,   KC_1 ,   KC_2 ,   KC_3 , KC_PLUS, _______,
		       _______, _______                                                 ,   KC_0 , _______,
					  _______, _______, _______, _______,
					  _______, _______, ADJUST , _______,
					  _______, _______, _______, _______ 
  ),
  [_LOWER] = LAYOUT_5x6(
     _______, _______, _______, _______, _______, _______,		_______, _______, _______, _______, _______, _______,
     _______, KC_ESC , KC_QUES, KC_UNDS, KC_F1  , KC_F2  ,		KC_F3  , KC_F4  , KC_MINS, KC_SLSH, KC_BSPC, _______,
     _______, KC_LSFT, KC_TAB , KC_PGUP, KC_F5  , KC_F6  ,		KC_F7  , KC_F8  , KC_HOME, KC_LALT, KC_ENT , _______,
     _______, KC_CLCK, KC_SLCK, KC_PGDN, KC_F7  , KC_F8  ,		KC_F11 , KC_F12 , KC_END , KC_INS , KC_SLSH, _______,
		       _______, _______                                                 , _______, _______,
					  _______, _______, _______, _______,
					  _______, ADJUST , _______, _______,
					  _______, _______, _______, _______ 
  ),
  [_RAISE] = LAYOUT_5x6(
     _______, _______, _______, _______, _______, _______,		_______, _______, _______, _______, _______, _______,
     KC_GRV ,  KC_1  ,   KC_2 ,  KC_3  ,   KC_4 ,   KC_5 ,		  KC_6 ,   KC_7 ,   KC_8 , KC_9   , KC_0   , KC_UNDS,
     KC_TILD, KC_EXLM,  KC_AT , KC_HASH, KC_DLR ,KC_PERC , 		KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_DQUO,
     _______, _______, _______, _______, _______, _______,		_______, _______, _______, _______, _______, KC_PIPE,
		       KC_LCBR, KC_RCBR                                                 , _______, _______,
					  KC_BSPC, _______, _______, _______,
					  _______, _______, ADJUST , _______,
					  _______, _______, _______, _______ 
  ),
  [_LOWER] = LAYOUT_5x6(
     KC_F11 ,  KC_F1 ,  KC_F2 ,  KC_F3 ,  KC_F4 ,  KC_F5 ,		 KC_F6 ,  KC_F7 ,  KC_F8 ,  KC_F9 , KC_F10 , KC_F11 ,
     _______, _______, _______, _______, _______, _______,		KC_HOME, KC_PGDN, KC_PGUP, KC_END , _______,  EU_AA ,
     _______, _______, _______, _______, _______, _______,		KC_LEFT, KC_DOWN,  KC_UP , KC_RGHT,  EU_OE ,  EU_AE ,
     _______, _______, _______, _______, _______, _______,		_______, _______, _______, _______, _______, _______,
		       _______, _______                                                 , _______, _______,
					  _______, _______, _______, KC_ENT ,
					  _______, ADJUST , _______, _______,
					  _______, _______, _______, _______ 
  ),*/
  [_ADJUST] = LAYOUT_5x6(
      RESET , _______, _______, _______, _______, _______,		_______, _______, _______, _______, _______,  RESET ,
     NK_TOGG, _______, _______, _______, _______, _______,		_______, _______, _______, _______, _______, NK_TOGG,
     PLOVER , _______, _______, _______, _______, _______,		_______, _______, _______, _______, _______, PLOVER ,
     _______, _______, _______, _______, _______, _______,		_______, _______, _______, _______, _______, _______,
		       _______, _______                                                 , _______, _______,
					  _______, _______, _______, _______,
					  _______, _______, _______, _______,
					  _______, _______, _______, _______ 
  ),
#ifdef STENO_ENABLE
  [_PLOVER] = LAYOUT_5x6(
     EXT_PLV, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,		XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,  RESET ,
     STN_N1 , STN_N2 , STN_N3 , STN_N4 , STN_N5 , STN_N6 ,		STN_N7 , STN_N8 , STN_N9 , STN_NA , STN_NB , STN_NC ,
     STN_FN , STN_S1 , STN_TL , STN_PL , STN_HL , STN_ST1,		STN_ST3, STN_FR , STN_PR , STN_LR , STN_TR , STN_DR ,
     XXXXXXX, STN_S2 , STN_KL , STN_WL , STN_RL , STN_ST2,		STN_ST4, STN_RR , STN_BR , STN_GR , STN_SR , STN_ZR ,
		       XXXXXXX, XXXXXXX                                                 , XXXXXXX, XXXXXXX,
					   STN_A ,  STN_O ,  STN_E ,  STN_U ,
					  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
					  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX 
  ),
#endif
};
/*

  [_TEMPLATE] = LAYOUT_5x6(
     _______, _______, _______, _______, _______, _______,		_______, _______, _______, _______, _______, _______,
     _______, _______, _______, _______, _______, _______,		_______, _______, _______, _______, _______, _______,
     _______, _______, _______, _______, _______, _______,		_______, _______, _______, _______, _______, _______,
     _______, _______, _______, _______, _______, _______,		_______, _______, _______, _______, _______, _______,
		       _______, _______                                                 , _______, _______,
					  _______, _______, _______, _______,
					  _______, _______, _______, _______,
					  _______, _______, _______, _______ 
  ),
*/

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
	case KVM_SW:
            if (record->event.pressed) {
	        SEND_STRING(SS_TAP(X_SLCK) SS_TAP(X_SLCK) SS_TAP(X_ENT));
            }
	break;
    }
    return true;
}
